version: '2'
services:
    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

    php-fpm:
        build:
            context: ./php-fpm
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace

    workspace:
        build:
            context: ./workspace
        tty: true

    volumes_source:
        build: ./volumes/application
        volumes:
            - ./source/:/var/www/html
