version: '2'
services:
    nginx:
        container_name: lemp_nginx
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
        volumes:
            - ./source:/var/www/html/
            - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d

    php-fpm:
        container_name: lemp_php
        build:
            context: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./source:/var/www/html/
