version: '2'
services:
    nginx:
        container_name: lemp_nginx
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
        volumes:
            - ./source:/var/www/html/
            - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d

    php-fpm:
        container_name: lemp_php
        build:
            context: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ./source:/var/www/html/
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:latest
        container_name: lemp_mysql
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3306:3306"

volumes:
    db-data:
        driver: local
